CREATE TABLE IF NOT EXISTS `country` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `code` char(3) NOT NULL DEFAULT '',
  `code2` char(2) NOT NULL DEFAULT '',
  `code3` char(3) NOT NULL DEFAULT '',
  `name_eng` varchar(100) NOT NULL DEFAULT '',
  `name_rus` varchar(100) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE KEY `code` (`code`),
  UNIQUE KEY `code2` (`code2`),
  UNIQUE KEY `code3` (`code3`),
  UNIQUE KEY `name_eng` (`name_eng`),
  UNIQUE KEY `name_rus` (`name_rus`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8;

INSERT INTO `country` (`id`, `code`, `code2`, `code3`, `name_eng`, `name_rus`) VALUES
(1, '840', 'US', 'USA', 'United States', 'США'),
(2, '124', 'CA', 'CAN', 'Canada', 'Канада'),
(3, '004', 'AF', 'AFG', 'Afghanistan', 'Афганистан'),
(4, '008', 'AL', 'ALB', 'Albania', 'Албания'),
(5, '012', 'DZ', 'DZA', 'Algeria', 'Алжир'),
(7, '020', 'AD', 'AND', 'Andorra', 'Андорра'),
(8, '024', 'AO', 'AGO', 'Angola', 'Ангола'),
(9, '660', 'AI', 'AIA', 'Anguilla', 'Ангилья'),
(10, '010', 'AQ', 'ATA', 'Antarctica', 'Антарктида'),
(11, '028', 'AG', 'ATG', 'Antigua and Barbuda', 'Антигуа и Барабуда'),
(12, '032', 'AR', 'ARG', 'Argentina', 'Аргентина'),
(13, '051', 'AM', 'ARM', 'Armenia', 'Армения'),
(14, '533', 'AW', 'ABW', 'Aruba', 'Аруба'),
(15, '036', 'AU', 'AUS', 'Australia', 'Австралия'),
(16, '040', 'AT', 'AUT', 'Austria', 'Австрия'),
(17, '031', 'AZ', 'AZE', 'Azerbaijan', 'Азербайджан'),
(18, '044', 'BS', 'BHS', 'Bahamas', 'Багамы'),
(19, '048', 'BH', 'BHR', 'Bahrain', 'Бахрейн'),
(20, '050', 'BD', 'BGD', 'Bangladesh', 'Бангладеш'),
(21, '052', 'BB', 'BRB', 'Barbados', 'Барбадос'),
(22, '112', 'BY', 'BLR', 'Belarus', 'Беларусь'),
(23, '056', 'BE', 'BEL', 'Belgium', 'Бельгия'),
(24, '084', 'BZ', 'BLZ', 'Belize', 'Белиз'),
(25, '204', 'BJ', 'BEN', 'Benin', 'Бенин'),
(26, '060', 'BM', 'BMU', 'Bermuda', 'Бермуды'),
(27, '064', 'BT', 'BTN', 'Bhutan', 'Бутан'),
(28, '068', 'BO', 'BOL', 'Bolivia', 'Боливия'),
(29, '070', 'BA', 'BIH', 'Bosnia and Herzegovina', 'Босния И Герцоговина'),
(30, '072', 'BW', 'BWA', 'Botswana', 'Ботсвана'),
(31, '074', 'BV', 'BVT', 'Bouvet Island', 'Остров Буве'),
(32, '076', 'BR', 'BRA', 'Brazil', 'Бразилия'),
(33, '086', 'IO', 'IOT', 'British lndian Ocean Territory', 'Британская етрритория В Индийском Океане'),
(34, '096', 'BN', 'BRN', 'Brunei Darussalam', 'Бруней-Даруссалам'),
(35, '100', 'BG', 'BGR', 'Bulgaria', 'Болгария'),
(36, '854', 'BF', 'BFA', 'Burkina Faso', 'Буркина-Фасо'),
(37, '108', 'BI', 'BDI', 'Burundi', 'Бурунди'),
(38, '116', 'KH', 'KHM', 'Cambodia', 'Камбоджа'),
(39, '120', 'CM', 'CMR', 'Cameroon', 'Камерун'),
(40, '132', 'CV', 'CPV', 'Cape Verde', 'Кабо-Верде'),
(41, '136', 'KY', 'CYM', 'Cayman Islands', 'Острова Кайман'),
(42, '140', 'CF', 'CAF', 'Central African Republic', 'Центрально-Африканская Республика'),
(43, '148', 'TD', 'TCD', 'Chad', 'Чад'),
(44, '152', 'CL', 'CHL', 'Chile', 'Чили'),
(45, '156', 'CN', 'CHN', 'China', 'Китай'),
(46, '162', 'CX', 'CXR', 'Christmas Island', 'Остров Рождества'),
(47, '166', 'CC', 'CCK', 'Cocos Islands', 'Кокосовые Острова'),
(48, '170', 'CO', 'COL', 'Colombia', 'Колумбия'),
(49, '174', 'KM', 'COM', 'Comoros', 'Коморы'),
(50, '178', 'CG', 'COG', 'Congo', 'Конго'),
(51, '184', 'CK', 'COK', 'Cook Islands', 'Острова Кука'),
(52, '188', 'CR', 'CRI', 'Costa Rica', 'Коста-Рика'),
(53, '191', 'HR', 'HRV', 'Croatia (Hrvatska)', 'Хорватия'),
(54, '192', 'CU', 'CUB', 'Cuba', 'Куба'),
(55, '196', 'CY', 'CYP', 'Cyprus', 'Кипр'),
(56, '203', 'CZ', 'CZE', 'Czech Republic', 'Чехия'),
(57, '208', 'DK', 'DNK', 'Denmark', 'Дания'),
(58, '262', 'DJ', 'DJI', 'Djibouti', 'Джибути'),
(59, '212', 'DM', 'DMA', 'Dominica', 'Доминика'),
(60, '214', 'DO', 'DOM', 'Dominican Republic', 'Доминиканская республика'),
(62, '218', 'EC', 'ECU', 'Ecuador', 'Эквадор'),
(63, '818', 'EG', 'EGY', 'Egypt', 'Египет'),
(64, '222', 'SV', 'SLV', 'El Salvador', 'Сальвадор'),
(65, '226', 'GQ', 'GNQ', 'Equatorial Guinea', 'Экваториальная Гвинея'),
(66, '232', 'ER', 'ERI', 'Eritrea', 'Эритрея'),
(67, '233', 'EE', 'EST', 'Estonia', 'Эстония'),
(68, '231', 'ET', 'ETH', 'Ethiopia', 'Эфиопия'),
(69, '238', 'FK', 'FLK', 'Falkland Islands (Malvinas)', 'Фолклендские Острова'),
(70, '234', 'FO', 'FRO', 'Faroe Islands', 'Фарерские Острова'),
(71, '242', 'FJ', 'FJI', 'Fiji', 'Фиджи'),
(72, '246', 'FI', 'FIN', 'Finland', 'Финляндия'),
(73, '250', 'FR', 'FRA', 'France', 'Франция'),
(75, '254', 'GF', 'GUF', 'French Guiana', 'Фанцузская Гвиана'),
(76, '258', 'PF', 'PYF', 'French Polynesia', 'Фанцузская Полинезия'),
(77, '260', 'TF', 'ATF', 'French Southern Territories', 'Фанцузские Южные Территории'),
(78, '266', 'GA', 'GAB', 'Gabon', 'Габон'),
(79, '270', 'GM', 'GMB', 'Gambia', 'Гамбия'),
(80, '268', 'GE', 'GEO', 'Georgia', 'Грузия'),
(81, '276', 'DE', 'DEU', 'Germany', 'Германия'),
(82, '288', 'GH', 'GHA', 'Ghana', 'Гана'),
(83, '292', 'GI', 'GIB', 'Gibraltar', 'Гибралтар'),
(84, '300', 'GR', 'GRC', 'Greece', 'Греция'),
(85, '304', 'GL', 'GRL', 'Greenland', 'Гренландия'),
(86, '308', 'GD', 'GRD', 'Grenada', 'Гренада'),
(87, '312', 'GP', 'GLP', 'Guadeloupe', 'Гваделупа'),
(88, '316', 'GU', 'GUM', 'Guam', 'Гуам'),
(89, '320', 'GT', 'GTM', 'Guatemala', 'Гватемала'),
(90, '324', 'GN', 'GIN', 'Guinea', 'Гвинея'),
(91, '624', 'GW', 'GNB', 'Guinea-Bissau', 'Гвинея-Бисау'),
(92, '328', 'GY', 'GUY', 'Guyana', 'Гайана'),
(93, '332', 'HT', 'HTI', 'Haiti', 'Гаити'),
(94, '334', 'HM', 'HMD', 'Heard and Mc Donald Islands', 'Остров Херд и Острова Макдональд'),
(95, '340', 'HN', 'HND', 'Honduras', 'Гондурас'),
(96, '344', 'HK', 'HKG', 'Hong Kong', 'Гонконг'),
(97, '348', 'HU', 'HUN', 'Hungary', 'Венгрия'),
(98, '352', 'IS', 'ISL', 'Iceland', 'Исландия'),
(99, '356', 'IN', 'IND', 'India', 'Индия'),
(100, '360', 'ID', 'IDN', 'Indonesia', 'Индонезия'),
(101, '364', 'IR', 'IRN', 'Iran (Islamic Republic of)', 'Иран'),
(102, '368', 'IQ', 'IRQ', 'Iraq', 'Ирак'),
(103, '372', 'IE', 'IRL', 'Ireland', 'Ирландия'),
(104, '376', 'IL', 'ISR', 'Israel', 'Израиль'),
(105, '380', 'IT', 'ITA', 'Italy', 'Италия'),
(106, '384', 'CI', 'CIV', 'Ivory Coast', 'Кот Д`ивуар'),
(107, '388', 'JM', 'JAM', 'Jamaica', 'Ямайка'),
(108, '392', 'JP', 'JPN', 'Japan', 'Япония'),
(109, '400', 'JO', 'JOR', 'Jordan', 'Иордания'),
(110, '398', 'KZ', 'KAZ', 'Kazakhstan', 'Казахстан'),
(111, '404', 'KE', 'KEN', 'Kenya', 'Кения'),
(112, '296', 'KI', 'KIR', 'Kiribati', 'Кирибати'),
(113, '408', 'KP', 'PRK', 'Korea, Democratic People''s Republic of', 'КНДР'),
(114, '410', 'KR', 'KOR', 'Korea, Republic of', 'Корея'),
(116, '414', 'KW', 'KWT', 'Kuwait', 'Кувейт'),
(117, '417', 'KG', 'KGZ', 'Kyrgyzstan', 'Кыргызстан'),
(118, '418', 'LA', 'LAO', 'Lao People''s Democratic Republic', 'Лаосская Республика'),
(119, '428', 'LV', 'LVA', 'Latvia', 'Латвия'),
(120, '422', 'LB', 'LBN', 'Lebanon', 'Ливан'),
(121, '426', 'LS', 'LSO', 'Lesotho', 'Лесото'),
(122, '430', 'LR', 'LBR', 'Liberia', 'Либерия'),
(123, '434', 'LY', 'LBY', 'Libyan Arab Jamahiriya', 'Ливия'),
(124, '438', 'LI', 'LIE', 'Liechtenstein', 'Лихтенштейн'),
(125, '440', 'LT', 'LTU', 'Lithuania', 'Литва'),
(126, '442', 'LU', 'LUX', 'Luxembourg', 'Люксембург'),
(127, '446', 'MO', 'MAC', 'Macau', 'Макао'),
(128, '807', 'MK', 'MKD', 'Macedonia', 'Македония'),
(129, '450', 'MG', 'MDG', 'Madagascar', 'Мадагаскар'),
(130, '454', 'MW', 'MWI', 'Malawi', 'Малави'),
(131, '458', 'MY', 'MYS', 'Malaysia', 'Малайзия'),
(132, '462', 'MV', 'MDV', 'Maldives', 'Мальдивы'),
(133, '466', 'ML', 'MLI', 'Mali', 'Мали'),
(134, '470', 'MT', 'MLT', 'Malta', 'Мальта'),
(135, '584', 'MH', 'MHL', 'Marshall Islands', 'Маршалловы Острова'),
(136, '474', 'MQ', 'MTQ', 'Martinique', 'Мартиника'),
(137, '478', 'MR', 'MRT', 'Mauritania', 'Мавритания'),
(138, '480', 'MU', 'MUS', 'Mauritius', 'Маврикий'),
(140, '484', 'MX', 'MEX', 'Mexico', 'Мексика'),
(141, '583', 'FM', 'FSM', 'Micronesia, Federated States of', 'Микронезия'),
(142, '498', 'MD', 'MDA', 'Moldova, Republic of', 'Молдова'),
(143, '492', 'MC', 'MCO', 'Monaco', 'Монако'),
(144, '496', 'MN', 'MNG', 'Mongolia', 'Монголия'),
(145, '499', 'ME', 'MNE', 'Montenegro', 'Черногория'),
(146, '500', 'MS', 'MSR', 'Montserrat', 'Монтсеррат'),
(147, '504', 'MA', 'MAR', 'Morocco', 'Марокко'),
(148, '508', 'MZ', 'MOZ', 'Mozambique', 'Мозамбик'),
(149, '104', 'MM', 'MMR', 'Myanmar', 'Мьянма'),
(150, '516', 'NA', 'NAM', 'Namibia', 'Намибия'),
(151, '520', 'NR', 'NRU', 'Nauru', 'Науру'),
(152, '524', 'NP', 'NPL', 'Nepal', 'Непал'),
(153, '528', 'NL', 'NLD', 'Netherlands', 'Нидерланды'),
(155, '540', 'NC', 'NCL', 'New Caledonia', 'Новая Каледония'),
(156, '554', 'NZ', 'NZL', 'New Zealand', 'Новая Зеландия'),
(157, '558', 'NI', 'NIC', 'Nicaragua', 'Никарагуа'),
(158, '562', 'NE', 'NER', 'Niger', 'Нигер'),
(159, '566', 'NG', 'NGA', 'Nigeria', 'Нигерия'),
(160, '570', 'NU', 'NIU', 'Niue', 'Ниуэ'),
(161, '574', 'NF', 'NFK', 'Norfork Island', 'Остров Норфолк'),
(162, '580', 'MP', 'MNP', 'Northern Mariana Islands', 'Северные Марианские Острова'),
(163, '578', 'NO', 'NOR', 'Norway', 'Норвегия'),
(164, '512', 'OM', 'OMN', 'Oman', 'Оман'),
(165, '586', 'PK', 'PAK', 'Pakistan', 'Пакистан'),
(166, '585', 'PW', 'PLW', 'Palau', 'Палау'),
(167, '591', 'PA', 'PAN', 'Panama', 'Панама'),
(168, '598', 'PG', 'PNG', 'Papua New Guinea', 'Папуа-Новая Гвинея'),
(169, '600', 'PY', 'PRY', 'Paraguay', 'Парагвай'),
(170, '604', 'PE', 'PER', 'Peru', 'Перу'),
(171, '608', 'PH', 'PHL', 'Philippines', 'Филлипины'),
(172, '612', 'PN', 'PCN', 'Pitcairn', 'Питкерн'),
(173, '616', 'PL', 'POL', 'Poland', 'Польша'),
(174, '620', 'PT', 'PRT', 'Portugal', 'Португалия'),
(175, '630', 'PR', 'PRI', 'Puerto Rico', 'Пуэрто-Рико'),
(176, '634', 'QA', 'QAT', 'Qatar', 'Катар'),
(177, '638', 'RE', 'REU', 'Reunion', 'Реюньон'),
(178, '642', 'RO', 'ROU', 'Romania', 'Румыния'),
(179, '643', 'RU', 'RUS', 'Russian Federation', 'Россия'),
(180, '646', 'RW', 'RWA', 'Rwanda', 'Руанда'),
(181, '659', 'KN', 'KNA', 'Saint Kitts and Nevis', 'Сент-Китс и Невис'),
(182, '662', 'LC', 'LCA', 'Saint Lucia', 'Сент-Люсия'),
(183, '670', 'VC', 'VCT', 'Saint Vincent and the Grenadines', 'Сент-Винсет и Гренадины'),
(184, '882', 'WS', 'WSM', 'Samoa', 'Самоа'),
(185, '674', 'SM', 'SMR', 'San Marino', 'Сан-Марино'),
(186, '678', 'ST', 'STP', 'Sao Tome and Principe', 'Сан-Томе и Принсипи'),
(187, '682', 'SA', 'SAU', 'Saudi Arabia', 'Саудовская Аравия'),
(188, '686', 'SN', 'SEN', 'Senegal', 'Сенегал'),
(189, '688', 'RS', 'SRB', 'Serbia', 'Сербия'),
(190, '690', 'SC', 'SYC', 'Seychelles', 'Сейшелы'),
(191, '694', 'SL', 'SLE', 'Sierra Leone', 'Сьерра-Леоне'),
(192, '702', 'SG', 'SGP', 'Singapore', 'Сингапур'),
(193, '703', 'SK', 'SVK', 'Slovakia', 'Словакия'),
(194, '705', 'SI', 'SVN', 'Slovenia', 'Словения'),
(195, '090', 'SB', 'SLB', 'Solomon Islands', 'Соломоновы Острова'),
(196, '706', 'SO', 'SOM', 'Somalia', 'Сомали'),
(197, '710', 'ZA', 'ZAF', 'South Africa', 'ЮАР'),
(198, '239', 'GS', 'SGS', 'South Georgia South Sandwich Islands', 'Южная Джорджия и Южные Сандвичевы Острова'),
(199, '724', 'ES', 'ESP', 'Spain', 'Испания'),
(200, '144', 'LK', 'LKA', 'Sri Lanka', 'Шри-Ланка'),
(201, '654', 'SH', 'SHN', 'St. Helena', 'Остров Вознесения'),
(202, '666', 'PM', 'SPM', 'St. Pierre and Miquelon', 'Сен-Пьер и Микелон'),
(203, '729', 'SD', 'SDN', 'Sudan', 'Судан'),
(204, '740', 'SR', 'SUR', 'Suriname', 'Суринам'),
(205, '744', 'SJ', 'SJM', 'Svalbarn and Jan Mayen Islands', 'Шпицберген и Ян Майен'),
(206, '748', 'SZ', 'SWZ', 'Swaziland', 'Свазиленд'),
(207, '752', 'SE', 'SWE', 'Sweden', 'Швеция'),
(208, '756', 'CH', 'CHE', 'Switzerland', 'Швейцария'),
(209, '760', 'SY', 'SYR', 'Syrian Arab Republic', 'Сирия'),
(210, '158', 'TW', 'TWN', 'Taiwan', 'Тайвань'),
(211, '762', 'TJ', 'TJK', 'Tajikistan', 'Таджикистан'),
(212, '834', 'TZ', 'TZA', 'Tanzania, United Republic of', 'Танзания'),
(213, '764', 'TH', 'THA', 'Thailand', 'Тайланд'),
(214, '768', 'TG', 'TGO', 'Togo', 'Того'),
(215, '772', 'TK', 'TKL', 'Tokelau', 'Токелау'),
(216, '776', 'TO', 'TON', 'Tonga', 'Тонга'),
(217, '780', 'TT', 'TTO', 'Trinidad and Tobago', 'Тринидад и Тобаго'),
(218, '788', 'TN', 'TUN', 'Tunisia', 'Тунис'),
(219, '792', 'TR', 'TUR', 'Turkey', 'Турция'),
(220, '795', 'TM', 'TKM', 'Turkmenistan', 'Туркмения'),
(221, '796', 'TC', 'TCA', 'Turks and Caicos Islands', 'Острова Теркс И Кайкос'),
(222, '798', 'TV', 'TUV', 'Tuvalu', 'Тувалу'),
(223, '800', 'UG', 'UGA', 'Uganda', 'Уганда'),
(224, '804', 'UA', 'UKR', 'Ukraine', 'Украина'),
(225, '784', 'AE', 'ARE', 'United Arab Emirates', 'ОАЭ'),
(226, '826', 'GB', 'GBR', 'United Kingdom', 'Великобритания'),
(228, '858', 'UY', 'URY', 'Uruguay', 'Уругвай'),
(229, '860', 'UZ', 'UZB', 'Uzbekistan', 'Узбекистан'),
(230, '548', 'VU', 'VUT', 'Vanuatu', 'Ванутау'),
(231, '336', 'VA', 'VAT', 'Vatican City State', 'Ватикан'),
(232, '862', 'VE', 'VEN', 'Venezuela', 'Венесуэла'),
(233, '704', 'VN', 'VNM', 'Vietnam', 'Вьетнам'),
(234, '092', 'VG', 'VGB', 'Virgin Islands (British)', 'Виргинские Острова (Британия)'),
(235, '850', 'VI', 'VIR', 'Virgin Islands (U.S.)', 'Виргинские Острова (США)'),
(236, '876', 'WF', 'WLF', 'Wallis and Futuna Islands', 'Уоллис и Футуна'),
(237, '732', 'EH', 'ESH', 'Western Sahara', 'Западная Сахара'),
(238, '887', 'YE', 'YEM', 'Yemen', 'Йемен'),
(241, '894', 'ZM', 'ZMB', 'Zambia', 'Замбия'),
(242, '716', 'ZW', 'ZWE', 'Zimbabwe', 'Зимбабве');